/*
Authlete API

Authlete API Document. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the TokenRevokeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenRevokeResponse{}

// TokenRevokeResponse struct for TokenRevokeResponse
type TokenRevokeResponse struct {
	// The number of tokens revoked
	Count *int32 `json:"count,omitempty"`
}

// NewTokenRevokeResponse instantiates a new TokenRevokeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenRevokeResponse() *TokenRevokeResponse {
	this := TokenRevokeResponse{}
	return &this
}

// NewTokenRevokeResponseWithDefaults instantiates a new TokenRevokeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenRevokeResponseWithDefaults() *TokenRevokeResponse {
	this := TokenRevokeResponse{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *TokenRevokeResponse) GetCount() int32 {
	if o == nil || isNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenRevokeResponse) GetCountOk() (*int32, bool) {
	if o == nil || isNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *TokenRevokeResponse) HasCount() bool {
	if o != nil && !isNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *TokenRevokeResponse) SetCount(v int32) {
	o.Count = &v
}

func (o TokenRevokeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenRevokeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableTokenRevokeResponse struct {
	value *TokenRevokeResponse
	isSet bool
}

func (v NullableTokenRevokeResponse) Get() *TokenRevokeResponse {
	return v.value
}

func (v *NullableTokenRevokeResponse) Set(val *TokenRevokeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenRevokeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenRevokeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenRevokeResponse(val *TokenRevokeResponse) *NullableTokenRevokeResponse {
	return &NullableTokenRevokeResponse{value: val, isSet: true}
}

func (v NullableTokenRevokeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenRevokeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


