/*
Authlete API

Authlete API Document. 

API version: 2.3.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the ClientFlagUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientFlagUpdateResponse{}

// ClientFlagUpdateResponse struct for ClientFlagUpdateResponse
type ClientFlagUpdateResponse struct {
	// The code which represents the result of the API call.
	ResultCode string `json:"resultCode"`
	// A short message which explains the result of the API call.
	ResultMessage string `json:"resultMessage"`
}

// NewClientFlagUpdateResponse instantiates a new ClientFlagUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientFlagUpdateResponse(resultCode string, resultMessage string) *ClientFlagUpdateResponse {
	this := ClientFlagUpdateResponse{}
	this.ResultCode = resultCode
	this.ResultMessage = resultMessage
	return &this
}

// NewClientFlagUpdateResponseWithDefaults instantiates a new ClientFlagUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientFlagUpdateResponseWithDefaults() *ClientFlagUpdateResponse {
	this := ClientFlagUpdateResponse{}
	return &this
}

// GetResultCode returns the ResultCode field value
func (o *ClientFlagUpdateResponse) GetResultCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResultCode
}

// GetResultCodeOk returns a tuple with the ResultCode field value
// and a boolean to check if the value has been set.
func (o *ClientFlagUpdateResponse) GetResultCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultCode, true
}

// SetResultCode sets field value
func (o *ClientFlagUpdateResponse) SetResultCode(v string) {
	o.ResultCode = v
}

// GetResultMessage returns the ResultMessage field value
func (o *ClientFlagUpdateResponse) GetResultMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResultMessage
}

// GetResultMessageOk returns a tuple with the ResultMessage field value
// and a boolean to check if the value has been set.
func (o *ClientFlagUpdateResponse) GetResultMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultMessage, true
}

// SetResultMessage sets field value
func (o *ClientFlagUpdateResponse) SetResultMessage(v string) {
	o.ResultMessage = v
}

func (o ClientFlagUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientFlagUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resultCode"] = o.ResultCode
	toSerialize["resultMessage"] = o.ResultMessage
	return toSerialize, nil
}

type NullableClientFlagUpdateResponse struct {
	value *ClientFlagUpdateResponse
	isSet bool
}

func (v NullableClientFlagUpdateResponse) Get() *ClientFlagUpdateResponse {
	return v.value
}

func (v *NullableClientFlagUpdateResponse) Set(val *ClientFlagUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientFlagUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientFlagUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientFlagUpdateResponse(val *ClientFlagUpdateResponse) *NullableClientFlagUpdateResponse {
	return &NullableClientFlagUpdateResponse{value: val, isSet: true}
}

func (v NullableClientFlagUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientFlagUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


