/*
Authlete API

Authlete API Document. 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the ServiceGetListLimitedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceGetListLimitedResponse{}

// ServiceGetListLimitedResponse struct for ServiceGetListLimitedResponse
type ServiceGetListLimitedResponse struct {
	// Start index (inclusive) of the result set. The default value is 0. Must not be a negative number. 
	Start *int32 `json:"start,omitempty"`
	// Start index (inclusive) of the result set. The default value is 0. Must not be a negative number. 
	End *int32 `json:"end,omitempty"`
	// Total number of services owned by the service owner. This doesn't mean the number of services contained in the response. 
	TotalCount *int32 `json:"totalCount,omitempty"`
	// An array of services. 
	Services []ServiceLimited `json:"services,omitempty"`
}

// NewServiceGetListLimitedResponse instantiates a new ServiceGetListLimitedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceGetListLimitedResponse() *ServiceGetListLimitedResponse {
	this := ServiceGetListLimitedResponse{}
	return &this
}

// NewServiceGetListLimitedResponseWithDefaults instantiates a new ServiceGetListLimitedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceGetListLimitedResponseWithDefaults() *ServiceGetListLimitedResponse {
	this := ServiceGetListLimitedResponse{}
	return &this
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *ServiceGetListLimitedResponse) GetStart() int32 {
	if o == nil || isNil(o.Start) {
		var ret int32
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGetListLimitedResponse) GetStartOk() (*int32, bool) {
	if o == nil || isNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *ServiceGetListLimitedResponse) HasStart() bool {
	if o != nil && !isNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given int32 and assigns it to the Start field.
func (o *ServiceGetListLimitedResponse) SetStart(v int32) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *ServiceGetListLimitedResponse) GetEnd() int32 {
	if o == nil || isNil(o.End) {
		var ret int32
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGetListLimitedResponse) GetEndOk() (*int32, bool) {
	if o == nil || isNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *ServiceGetListLimitedResponse) HasEnd() bool {
	if o != nil && !isNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given int32 and assigns it to the End field.
func (o *ServiceGetListLimitedResponse) SetEnd(v int32) {
	o.End = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *ServiceGetListLimitedResponse) GetTotalCount() int32 {
	if o == nil || isNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGetListLimitedResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil || isNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *ServiceGetListLimitedResponse) HasTotalCount() bool {
	if o != nil && !isNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *ServiceGetListLimitedResponse) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ServiceGetListLimitedResponse) GetServices() []ServiceLimited {
	if o == nil || isNil(o.Services) {
		var ret []ServiceLimited
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceGetListLimitedResponse) GetServicesOk() ([]ServiceLimited, bool) {
	if o == nil || isNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ServiceGetListLimitedResponse) HasServices() bool {
	if o != nil && !isNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []ServiceLimited and assigns it to the Services field.
func (o *ServiceGetListLimitedResponse) SetServices(v []ServiceLimited) {
	o.Services = v
}

func (o ServiceGetListLimitedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceGetListLimitedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !isNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !isNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	if !isNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	return toSerialize, nil
}

type NullableServiceGetListLimitedResponse struct {
	value *ServiceGetListLimitedResponse
	isSet bool
}

func (v NullableServiceGetListLimitedResponse) Get() *ServiceGetListLimitedResponse {
	return v.value
}

func (v *NullableServiceGetListLimitedResponse) Set(val *ServiceGetListLimitedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceGetListLimitedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceGetListLimitedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceGetListLimitedResponse(val *ServiceGetListLimitedResponse) *NullableServiceGetListLimitedResponse {
	return &NullableServiceGetListLimitedResponse{value: val, isSet: true}
}

func (v NullableServiceGetListLimitedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceGetListLimitedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


