/*
Authlete API

Authlete API Document. 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the VciJwksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VciJwksRequest{}

// VciJwksRequest struct for VciJwksRequest
type VciJwksRequest struct {
	// The flag indicating whether the metadata is written in the pretty format or not.
	Pretty bool `json:"pretty"`
}

// NewVciJwksRequest instantiates a new VciJwksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVciJwksRequest(pretty bool) *VciJwksRequest {
	this := VciJwksRequest{}
	this.Pretty = pretty
	return &this
}

// NewVciJwksRequestWithDefaults instantiates a new VciJwksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVciJwksRequestWithDefaults() *VciJwksRequest {
	this := VciJwksRequest{}
	return &this
}

// GetPretty returns the Pretty field value
func (o *VciJwksRequest) GetPretty() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Pretty
}

// GetPrettyOk returns a tuple with the Pretty field value
// and a boolean to check if the value has been set.
func (o *VciJwksRequest) GetPrettyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pretty, true
}

// SetPretty sets field value
func (o *VciJwksRequest) SetPretty(v bool) {
	o.Pretty = v
}

func (o VciJwksRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VciJwksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pretty"] = o.Pretty
	return toSerialize, nil
}

type NullableVciJwksRequest struct {
	value *VciJwksRequest
	isSet bool
}

func (v NullableVciJwksRequest) Get() *VciJwksRequest {
	return v.value
}

func (v *NullableVciJwksRequest) Set(val *VciJwksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVciJwksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVciJwksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVciJwksRequest(val *VciJwksRequest) *NullableVciJwksRequest {
	return &NullableVciJwksRequest{value: val, isSet: true}
}

func (v NullableVciJwksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVciJwksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


