/*
Authlete API

Authlete API Document.

API version: 2.3.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the ClientRegistrationDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientRegistrationDeleteRequest{}

// ClientRegistrationDeleteRequest struct for ClientRegistrationDeleteRequest
type ClientRegistrationDeleteRequest struct {
	// Client ID.
	ClientId string `json:"clientId"`
	// Client registration access token.
	Token string `json:"token"`
}

// NewClientRegistrationDeleteRequest instantiates a new ClientRegistrationDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientRegistrationDeleteRequest(clientId string, token string) *ClientRegistrationDeleteRequest {
	this := ClientRegistrationDeleteRequest{}
	this.ClientId = clientId
	this.Token = token
	return &this
}

// NewClientRegistrationDeleteRequestWithDefaults instantiates a new ClientRegistrationDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientRegistrationDeleteRequestWithDefaults() *ClientRegistrationDeleteRequest {
	this := ClientRegistrationDeleteRequest{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *ClientRegistrationDeleteRequest) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *ClientRegistrationDeleteRequest) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *ClientRegistrationDeleteRequest) SetClientId(v string) {
	o.ClientId = v
}

// GetToken returns the Token field value
func (o *ClientRegistrationDeleteRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *ClientRegistrationDeleteRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ClientRegistrationDeleteRequest) SetToken(v string) {
	o.Token = v
}

func (o ClientRegistrationDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientRegistrationDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientId"] = o.ClientId
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

type NullableClientRegistrationDeleteRequest struct {
	value *ClientRegistrationDeleteRequest
	isSet bool
}

func (v NullableClientRegistrationDeleteRequest) Get() *ClientRegistrationDeleteRequest {
	return v.value
}

func (v *NullableClientRegistrationDeleteRequest) Set(val *ClientRegistrationDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClientRegistrationDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClientRegistrationDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientRegistrationDeleteRequest(val *ClientRegistrationDeleteRequest) *NullableClientRegistrationDeleteRequest {
	return &NullableClientRegistrationDeleteRequest{value: val, isSet: true}
}

func (v NullableClientRegistrationDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientRegistrationDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
