/*
Authlete API

Authlete API Document. 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the AuthorizationTicketInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizationTicketInfoResponse{}

// AuthorizationTicketInfoResponse struct for AuthorizationTicketInfoResponse
type AuthorizationTicketInfoResponse struct {
	// Information about the ticket.
	Info *string `json:"info,omitempty"`
	// The result of the `/auth/authorization/ticket/info` API call.
	Action *string `json:"action,omitempty"`
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitempty"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitempty"`
}

// NewAuthorizationTicketInfoResponse instantiates a new AuthorizationTicketInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationTicketInfoResponse() *AuthorizationTicketInfoResponse {
	this := AuthorizationTicketInfoResponse{}
	return &this
}

// NewAuthorizationTicketInfoResponseWithDefaults instantiates a new AuthorizationTicketInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationTicketInfoResponseWithDefaults() *AuthorizationTicketInfoResponse {
	this := AuthorizationTicketInfoResponse{}
	return &this
}

// GetInfo returns the Info field value if set, zero value otherwise.
func (o *AuthorizationTicketInfoResponse) GetInfo() string {
	if o == nil || isNil(o.Info) {
		var ret string
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationTicketInfoResponse) GetInfoOk() (*string, bool) {
	if o == nil || isNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *AuthorizationTicketInfoResponse) HasInfo() bool {
	if o != nil && !isNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given string and assigns it to the Info field.
func (o *AuthorizationTicketInfoResponse) SetInfo(v string) {
	o.Info = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *AuthorizationTicketInfoResponse) GetAction() string {
	if o == nil || isNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationTicketInfoResponse) GetActionOk() (*string, bool) {
	if o == nil || isNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *AuthorizationTicketInfoResponse) HasAction() bool {
	if o != nil && !isNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *AuthorizationTicketInfoResponse) SetAction(v string) {
	o.Action = &v
}

// GetResultCode returns the ResultCode field value if set, zero value otherwise.
func (o *AuthorizationTicketInfoResponse) GetResultCode() string {
	if o == nil || isNil(o.ResultCode) {
		var ret string
		return ret
	}
	return *o.ResultCode
}

// GetResultCodeOk returns a tuple with the ResultCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationTicketInfoResponse) GetResultCodeOk() (*string, bool) {
	if o == nil || isNil(o.ResultCode) {
		return nil, false
	}
	return o.ResultCode, true
}

// HasResultCode returns a boolean if a field has been set.
func (o *AuthorizationTicketInfoResponse) HasResultCode() bool {
	if o != nil && !isNil(o.ResultCode) {
		return true
	}

	return false
}

// SetResultCode gets a reference to the given string and assigns it to the ResultCode field.
func (o *AuthorizationTicketInfoResponse) SetResultCode(v string) {
	o.ResultCode = &v
}

// GetResultMessage returns the ResultMessage field value if set, zero value otherwise.
func (o *AuthorizationTicketInfoResponse) GetResultMessage() string {
	if o == nil || isNil(o.ResultMessage) {
		var ret string
		return ret
	}
	return *o.ResultMessage
}

// GetResultMessageOk returns a tuple with the ResultMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationTicketInfoResponse) GetResultMessageOk() (*string, bool) {
	if o == nil || isNil(o.ResultMessage) {
		return nil, false
	}
	return o.ResultMessage, true
}

// HasResultMessage returns a boolean if a field has been set.
func (o *AuthorizationTicketInfoResponse) HasResultMessage() bool {
	if o != nil && !isNil(o.ResultMessage) {
		return true
	}

	return false
}

// SetResultMessage gets a reference to the given string and assigns it to the ResultMessage field.
func (o *AuthorizationTicketInfoResponse) SetResultMessage(v string) {
	o.ResultMessage = &v
}

func (o AuthorizationTicketInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizationTicketInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Info) {
		toSerialize["info"] = o.Info
	}
	if !isNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !isNil(o.ResultCode) {
		toSerialize["resultCode"] = o.ResultCode
	}
	if !isNil(o.ResultMessage) {
		toSerialize["resultMessage"] = o.ResultMessage
	}
	return toSerialize, nil
}

type NullableAuthorizationTicketInfoResponse struct {
	value *AuthorizationTicketInfoResponse
	isSet bool
}

func (v NullableAuthorizationTicketInfoResponse) Get() *AuthorizationTicketInfoResponse {
	return v.value
}

func (v *NullableAuthorizationTicketInfoResponse) Set(val *AuthorizationTicketInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationTicketInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationTicketInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationTicketInfoResponse(val *AuthorizationTicketInfoResponse) *NullableAuthorizationTicketInfoResponse {
	return &NullableAuthorizationTicketInfoResponse{value: val, isSet: true}
}

func (v NullableAuthorizationTicketInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationTicketInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


