/*
Authlete API

Authlete API Document.

API version: 2.3.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the InfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfoResponse{}

// InfoResponse struct for InfoResponse
type InfoResponse struct {
	// The server version.
	Version string `json:"version"`
	// the features that the server supports.
	Features []string `json:"features"`
}

// NewInfoResponse instantiates a new InfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfoResponse(version string, features []string) *InfoResponse {
	this := InfoResponse{}
	this.Version = version
	this.Features = features
	return &this
}

// NewInfoResponseWithDefaults instantiates a new InfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfoResponseWithDefaults() *InfoResponse {
	this := InfoResponse{}
	return &this
}

// GetVersion returns the Version field value
func (o *InfoResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *InfoResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *InfoResponse) SetVersion(v string) {
	o.Version = v
}

// GetFeatures returns the Features field value
func (o *InfoResponse) GetFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *InfoResponse) GetFeaturesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *InfoResponse) SetFeatures(v []string) {
	o.Features = v
}

func (o InfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["features"] = o.Features
	return toSerialize, nil
}

type NullableInfoResponse struct {
	value *InfoResponse
	isSet bool
}

func (v NullableInfoResponse) Get() *InfoResponse {
	return v.value
}

func (v *NullableInfoResponse) Set(val *InfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfoResponse(val *InfoResponse) *NullableInfoResponse {
	return &NullableInfoResponse{value: val, isSet: true}
}

func (v NullableInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
