/*
Authlete API

Authlete API Document. 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the Hsk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Hsk{}

// Hsk Holds information about a key managed in an HSM (Hardware Security Module) 
type Hsk struct {
	// The key type (EC or RSA) 
	Kty *string `json:"kty,omitempty"`
	// Get the use of the key on the HSM. When the key use is \"sig\" (signature), the private key on the HSM is used to sign data and the corresponding public key is used to verify the signature. When the key use is \"enc\" (encryption), the private key on the HSM is used to decrypt encrypted data which have been encrypted with the corresponding public key 
	Use *string `json:"use,omitempty"`
	// Key ID for the key on the HSM. 
	Kid *string `json:"kid,omitempty"`
	// The name of the HSM. The identifier for the HSM that sits behind the Authlete server. For example, \"google\". 
	HsmName *string `json:"hsmName,omitempty"`
	// The handle for the key on the HSM. A handle is a base64url-encoded 256-bit random value (43 letters) which is assigned by Authlete on the call of the /api/hsk/create API 
	Handle *string `json:"handle,omitempty"`
	// The public key that corresponds to the key on the HSM.
	PublicKey *string `json:"publicKey,omitempty"`
}

// NewHsk instantiates a new Hsk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHsk() *Hsk {
	this := Hsk{}
	return &this
}

// NewHskWithDefaults instantiates a new Hsk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHskWithDefaults() *Hsk {
	this := Hsk{}
	return &this
}

// GetKty returns the Kty field value if set, zero value otherwise.
func (o *Hsk) GetKty() string {
	if o == nil || isNil(o.Kty) {
		var ret string
		return ret
	}
	return *o.Kty
}

// GetKtyOk returns a tuple with the Kty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hsk) GetKtyOk() (*string, bool) {
	if o == nil || isNil(o.Kty) {
		return nil, false
	}
	return o.Kty, true
}

// HasKty returns a boolean if a field has been set.
func (o *Hsk) HasKty() bool {
	if o != nil && !isNil(o.Kty) {
		return true
	}

	return false
}

// SetKty gets a reference to the given string and assigns it to the Kty field.
func (o *Hsk) SetKty(v string) {
	o.Kty = &v
}

// GetUse returns the Use field value if set, zero value otherwise.
func (o *Hsk) GetUse() string {
	if o == nil || isNil(o.Use) {
		var ret string
		return ret
	}
	return *o.Use
}

// GetUseOk returns a tuple with the Use field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hsk) GetUseOk() (*string, bool) {
	if o == nil || isNil(o.Use) {
		return nil, false
	}
	return o.Use, true
}

// HasUse returns a boolean if a field has been set.
func (o *Hsk) HasUse() bool {
	if o != nil && !isNil(o.Use) {
		return true
	}

	return false
}

// SetUse gets a reference to the given string and assigns it to the Use field.
func (o *Hsk) SetUse(v string) {
	o.Use = &v
}

// GetKid returns the Kid field value if set, zero value otherwise.
func (o *Hsk) GetKid() string {
	if o == nil || isNil(o.Kid) {
		var ret string
		return ret
	}
	return *o.Kid
}

// GetKidOk returns a tuple with the Kid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hsk) GetKidOk() (*string, bool) {
	if o == nil || isNil(o.Kid) {
		return nil, false
	}
	return o.Kid, true
}

// HasKid returns a boolean if a field has been set.
func (o *Hsk) HasKid() bool {
	if o != nil && !isNil(o.Kid) {
		return true
	}

	return false
}

// SetKid gets a reference to the given string and assigns it to the Kid field.
func (o *Hsk) SetKid(v string) {
	o.Kid = &v
}

// GetHsmName returns the HsmName field value if set, zero value otherwise.
func (o *Hsk) GetHsmName() string {
	if o == nil || isNil(o.HsmName) {
		var ret string
		return ret
	}
	return *o.HsmName
}

// GetHsmNameOk returns a tuple with the HsmName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hsk) GetHsmNameOk() (*string, bool) {
	if o == nil || isNil(o.HsmName) {
		return nil, false
	}
	return o.HsmName, true
}

// HasHsmName returns a boolean if a field has been set.
func (o *Hsk) HasHsmName() bool {
	if o != nil && !isNil(o.HsmName) {
		return true
	}

	return false
}

// SetHsmName gets a reference to the given string and assigns it to the HsmName field.
func (o *Hsk) SetHsmName(v string) {
	o.HsmName = &v
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *Hsk) GetHandle() string {
	if o == nil || isNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hsk) GetHandleOk() (*string, bool) {
	if o == nil || isNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *Hsk) HasHandle() bool {
	if o != nil && !isNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *Hsk) SetHandle(v string) {
	o.Handle = &v
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *Hsk) GetPublicKey() string {
	if o == nil || isNil(o.PublicKey) {
		var ret string
		return ret
	}
	return *o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hsk) GetPublicKeyOk() (*string, bool) {
	if o == nil || isNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *Hsk) HasPublicKey() bool {
	if o != nil && !isNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given string and assigns it to the PublicKey field.
func (o *Hsk) SetPublicKey(v string) {
	o.PublicKey = &v
}

func (o Hsk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Hsk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Kty) {
		toSerialize["kty"] = o.Kty
	}
	if !isNil(o.Use) {
		toSerialize["use"] = o.Use
	}
	if !isNil(o.Kid) {
		toSerialize["kid"] = o.Kid
	}
	if !isNil(o.HsmName) {
		toSerialize["hsmName"] = o.HsmName
	}
	if !isNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	if !isNil(o.PublicKey) {
		toSerialize["publicKey"] = o.PublicKey
	}
	return toSerialize, nil
}

type NullableHsk struct {
	value *Hsk
	isSet bool
}

func (v NullableHsk) Get() *Hsk {
	return v.value
}

func (v *NullableHsk) Set(val *Hsk) {
	v.value = val
	v.isSet = true
}

func (v NullableHsk) IsSet() bool {
	return v.isSet
}

func (v *NullableHsk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHsk(val *Hsk) *NullableHsk {
	return &NullableHsk{value: val, isSet: true}
}

func (v NullableHsk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHsk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


