/*
Authlete API

Authlete API Document. 

API version: 2.2.25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// PushedAuthReqResponse struct for PushedAuthReqResponse
type PushedAuthReqResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitempty"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitempty"`
	// The next action that the authorization server implementation should take. Any other value other than \"CREATED\" should be handled as unsuccessful result.
	Action *string `json:"action,omitempty"`
	// The request_uri created to the client to be used as request_uri on the authorize call. 
	RequestUri *string `json:"requestUri,omitempty"`
	// The content that the authorization server implementation is to return to the client application.
	ResponseContent *string `json:"responseContent,omitempty"`
}

// NewPushedAuthReqResponse instantiates a new PushedAuthReqResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushedAuthReqResponse() *PushedAuthReqResponse {
	this := PushedAuthReqResponse{}
	return &this
}

// NewPushedAuthReqResponseWithDefaults instantiates a new PushedAuthReqResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushedAuthReqResponseWithDefaults() *PushedAuthReqResponse {
	this := PushedAuthReqResponse{}
	return &this
}

// GetResultCode returns the ResultCode field value if set, zero value otherwise.
func (o *PushedAuthReqResponse) GetResultCode() string {
	if o == nil || o.ResultCode == nil {
		var ret string
		return ret
	}
	return *o.ResultCode
}

// GetResultCodeOk returns a tuple with the ResultCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushedAuthReqResponse) GetResultCodeOk() (*string, bool) {
	if o == nil || o.ResultCode == nil {
		return nil, false
	}
	return o.ResultCode, true
}

// HasResultCode returns a boolean if a field has been set.
func (o *PushedAuthReqResponse) HasResultCode() bool {
	if o != nil && o.ResultCode != nil {
		return true
	}

	return false
}

// SetResultCode gets a reference to the given string and assigns it to the ResultCode field.
func (o *PushedAuthReqResponse) SetResultCode(v string) {
	o.ResultCode = &v
}

// GetResultMessage returns the ResultMessage field value if set, zero value otherwise.
func (o *PushedAuthReqResponse) GetResultMessage() string {
	if o == nil || o.ResultMessage == nil {
		var ret string
		return ret
	}
	return *o.ResultMessage
}

// GetResultMessageOk returns a tuple with the ResultMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushedAuthReqResponse) GetResultMessageOk() (*string, bool) {
	if o == nil || o.ResultMessage == nil {
		return nil, false
	}
	return o.ResultMessage, true
}

// HasResultMessage returns a boolean if a field has been set.
func (o *PushedAuthReqResponse) HasResultMessage() bool {
	if o != nil && o.ResultMessage != nil {
		return true
	}

	return false
}

// SetResultMessage gets a reference to the given string and assigns it to the ResultMessage field.
func (o *PushedAuthReqResponse) SetResultMessage(v string) {
	o.ResultMessage = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *PushedAuthReqResponse) GetAction() string {
	if o == nil || o.Action == nil {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushedAuthReqResponse) GetActionOk() (*string, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *PushedAuthReqResponse) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *PushedAuthReqResponse) SetAction(v string) {
	o.Action = &v
}

// GetRequestUri returns the RequestUri field value if set, zero value otherwise.
func (o *PushedAuthReqResponse) GetRequestUri() string {
	if o == nil || o.RequestUri == nil {
		var ret string
		return ret
	}
	return *o.RequestUri
}

// GetRequestUriOk returns a tuple with the RequestUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushedAuthReqResponse) GetRequestUriOk() (*string, bool) {
	if o == nil || o.RequestUri == nil {
		return nil, false
	}
	return o.RequestUri, true
}

// HasRequestUri returns a boolean if a field has been set.
func (o *PushedAuthReqResponse) HasRequestUri() bool {
	if o != nil && o.RequestUri != nil {
		return true
	}

	return false
}

// SetRequestUri gets a reference to the given string and assigns it to the RequestUri field.
func (o *PushedAuthReqResponse) SetRequestUri(v string) {
	o.RequestUri = &v
}

// GetResponseContent returns the ResponseContent field value if set, zero value otherwise.
func (o *PushedAuthReqResponse) GetResponseContent() string {
	if o == nil || o.ResponseContent == nil {
		var ret string
		return ret
	}
	return *o.ResponseContent
}

// GetResponseContentOk returns a tuple with the ResponseContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushedAuthReqResponse) GetResponseContentOk() (*string, bool) {
	if o == nil || o.ResponseContent == nil {
		return nil, false
	}
	return o.ResponseContent, true
}

// HasResponseContent returns a boolean if a field has been set.
func (o *PushedAuthReqResponse) HasResponseContent() bool {
	if o != nil && o.ResponseContent != nil {
		return true
	}

	return false
}

// SetResponseContent gets a reference to the given string and assigns it to the ResponseContent field.
func (o *PushedAuthReqResponse) SetResponseContent(v string) {
	o.ResponseContent = &v
}

func (o PushedAuthReqResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ResultCode != nil {
		toSerialize["resultCode"] = o.ResultCode
	}
	if o.ResultMessage != nil {
		toSerialize["resultMessage"] = o.ResultMessage
	}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if o.RequestUri != nil {
		toSerialize["requestUri"] = o.RequestUri
	}
	if o.ResponseContent != nil {
		toSerialize["responseContent"] = o.ResponseContent
	}
	return json.Marshal(toSerialize)
}

type NullablePushedAuthReqResponse struct {
	value *PushedAuthReqResponse
	isSet bool
}

func (v NullablePushedAuthReqResponse) Get() *PushedAuthReqResponse {
	return v.value
}

func (v *NullablePushedAuthReqResponse) Set(val *PushedAuthReqResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePushedAuthReqResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePushedAuthReqResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushedAuthReqResponse(val *PushedAuthReqResponse) *NullablePushedAuthReqResponse {
	return &NullablePushedAuthReqResponse{value: val, isSet: true}
}

func (v NullablePushedAuthReqResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushedAuthReqResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


