/*
Authlete API

Authlete API Document. 

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authlete

import (
	"encoding/json"
)

// checks if the ClientAuthorizationGetListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientAuthorizationGetListResponse{}

// ClientAuthorizationGetListResponse struct for ClientAuthorizationGetListResponse
type ClientAuthorizationGetListResponse struct {
	// Start index of search results (inclusive). 
	Start *int32 `json:"start,omitempty"`
	// End index of search results (exclusive). 
	End *int32 `json:"end,omitempty"`
	// Unique ID of a client developer. 
	Developer *string `json:"developer,omitempty"`
	// Unique user ID of an end-user. 
	Subject *string `json:"subject,omitempty"`
	// Unique ID of a client developer. 
	TotalCount *int32 `json:"totalCount,omitempty"`
	// An array of clients. 
	Clients []ClientLimited `json:"clients,omitempty"`
}

// NewClientAuthorizationGetListResponse instantiates a new ClientAuthorizationGetListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientAuthorizationGetListResponse() *ClientAuthorizationGetListResponse {
	this := ClientAuthorizationGetListResponse{}
	return &this
}

// NewClientAuthorizationGetListResponseWithDefaults instantiates a new ClientAuthorizationGetListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientAuthorizationGetListResponseWithDefaults() *ClientAuthorizationGetListResponse {
	this := ClientAuthorizationGetListResponse{}
	return &this
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *ClientAuthorizationGetListResponse) GetStart() int32 {
	if o == nil || isNil(o.Start) {
		var ret int32
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAuthorizationGetListResponse) GetStartOk() (*int32, bool) {
	if o == nil || isNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *ClientAuthorizationGetListResponse) HasStart() bool {
	if o != nil && !isNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given int32 and assigns it to the Start field.
func (o *ClientAuthorizationGetListResponse) SetStart(v int32) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *ClientAuthorizationGetListResponse) GetEnd() int32 {
	if o == nil || isNil(o.End) {
		var ret int32
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAuthorizationGetListResponse) GetEndOk() (*int32, bool) {
	if o == nil || isNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *ClientAuthorizationGetListResponse) HasEnd() bool {
	if o != nil && !isNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given int32 and assigns it to the End field.
func (o *ClientAuthorizationGetListResponse) SetEnd(v int32) {
	o.End = &v
}

// GetDeveloper returns the Developer field value if set, zero value otherwise.
func (o *ClientAuthorizationGetListResponse) GetDeveloper() string {
	if o == nil || isNil(o.Developer) {
		var ret string
		return ret
	}
	return *o.Developer
}

// GetDeveloperOk returns a tuple with the Developer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAuthorizationGetListResponse) GetDeveloperOk() (*string, bool) {
	if o == nil || isNil(o.Developer) {
		return nil, false
	}
	return o.Developer, true
}

// HasDeveloper returns a boolean if a field has been set.
func (o *ClientAuthorizationGetListResponse) HasDeveloper() bool {
	if o != nil && !isNil(o.Developer) {
		return true
	}

	return false
}

// SetDeveloper gets a reference to the given string and assigns it to the Developer field.
func (o *ClientAuthorizationGetListResponse) SetDeveloper(v string) {
	o.Developer = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *ClientAuthorizationGetListResponse) GetSubject() string {
	if o == nil || isNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAuthorizationGetListResponse) GetSubjectOk() (*string, bool) {
	if o == nil || isNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *ClientAuthorizationGetListResponse) HasSubject() bool {
	if o != nil && !isNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *ClientAuthorizationGetListResponse) SetSubject(v string) {
	o.Subject = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *ClientAuthorizationGetListResponse) GetTotalCount() int32 {
	if o == nil || isNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAuthorizationGetListResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil || isNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *ClientAuthorizationGetListResponse) HasTotalCount() bool {
	if o != nil && !isNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *ClientAuthorizationGetListResponse) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetClients returns the Clients field value if set, zero value otherwise.
func (o *ClientAuthorizationGetListResponse) GetClients() []ClientLimited {
	if o == nil || isNil(o.Clients) {
		var ret []ClientLimited
		return ret
	}
	return o.Clients
}

// GetClientsOk returns a tuple with the Clients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAuthorizationGetListResponse) GetClientsOk() ([]ClientLimited, bool) {
	if o == nil || isNil(o.Clients) {
		return nil, false
	}
	return o.Clients, true
}

// HasClients returns a boolean if a field has been set.
func (o *ClientAuthorizationGetListResponse) HasClients() bool {
	if o != nil && !isNil(o.Clients) {
		return true
	}

	return false
}

// SetClients gets a reference to the given []ClientLimited and assigns it to the Clients field.
func (o *ClientAuthorizationGetListResponse) SetClients(v []ClientLimited) {
	o.Clients = v
}

func (o ClientAuthorizationGetListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientAuthorizationGetListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !isNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !isNil(o.Developer) {
		toSerialize["developer"] = o.Developer
	}
	if !isNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !isNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	if !isNil(o.Clients) {
		toSerialize["clients"] = o.Clients
	}
	return toSerialize, nil
}

type NullableClientAuthorizationGetListResponse struct {
	value *ClientAuthorizationGetListResponse
	isSet bool
}

func (v NullableClientAuthorizationGetListResponse) Get() *ClientAuthorizationGetListResponse {
	return v.value
}

func (v *NullableClientAuthorizationGetListResponse) Set(val *ClientAuthorizationGetListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientAuthorizationGetListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientAuthorizationGetListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientAuthorizationGetListResponse(val *ClientAuthorizationGetListResponse) *NullableClientAuthorizationGetListResponse {
	return &NullableClientAuthorizationGetListResponse{value: val, isSet: true}
}

func (v NullableClientAuthorizationGetListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientAuthorizationGetListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


