# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  test:
    name: Client Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        # list whatever Terraform versions here you would like to support
        goversion:
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.goversion }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go mod tidy

    - name: client tests shared cloud
      timeout-minutes: 10
      env:
        AUTHLETE_API_SERVER: ${{ secrets.AUTHLETE_API_SERVER }}
        AUTHLETE_SO_KEY: ${{ secrets.AUTHLETE_SO_KEY }}
        AUTHLETE_SO_SECRET: ${{ secrets.AUTHLETE_SO_SECRET }}

      run: |
        go test -v -cover ./...

    - name: client tests fapi-dev
      timeout-minutes: 10
      env:
        AUTHLETE_API_SERVER: ${{ secrets.AUTHLETE_FAPI_DEV_API_SERVER }}
        AUTHLETE_SO_KEY: ${{ secrets.AUTHLETE_FAPI_DEV_SO_KEY }}
        AUTHLETE_SO_SECRET: ${{ secrets.AUTHLETE_FAPI_DEV_SO_SECRET }}

      run: |
        go test -v -cover ./...
